### ISSUE TITLE
NTFS compression issue with SQL Server

### ISSUE THREAD

**Issue by CMCDragonkai** [riezebosch/BoxstarterPackages#12]
> SQL Server cannot be installed into a folder that is NTFS compressed. An error that occurs is this: `The specified directory, "C:\Program Files\Microsoft SQL Server\", for the INSTALLSHAREDDIR parameter is not valid because this directory is compressed or is in a compressed directory. Specify a directory that is not compressed.`. Please add a check to the installer powershell script to check if the directory being installed in is a compressed folder or not, and then fail the installation but request that the user first switch off NTFS compression for "C:\Program Files\Microsoft SQL Server\" or the relevant 32 bit path.

> It's apparently possible to use the `compact.exe` to show whether a folder is compressed or not. Use `compact /q 'C:\Program Files\Microsoft SQL Server\'` There's a line that tells you whether new files will be compressed or not.

**Comment by riezebosch** [comment]
But that error is already telling you why it fails install. What's the added value to make the package check this? It's also nearly impossible to find out the directory that the instance will be installed because it can be specified from the command line, the default program files folder location or via a configuration file...
